### ISSUE TITLE
My server is cuda10.0 installed, and my virtual environment is pytorch1.6 of cuda10.2 installed.

### ISSUE THREAD

**Issue by xiaozhangya** [thomasbrandon/mish-cuda#6]
My server is cuda10.0 installed, and my virtual environment is pytorch1.6 of cuda10.2 installed. In this way, I installed mish-cuda in my virtual environment and reported an error, but failed to install successfully. The error is as follows:
![1604472610(1)](https://user-images.githubusercontent.com/52917741/98078451-11b23800-1ead-11eb-9d90-8146bc048b9c.png)

**Comment by thomasbrandon** [comment]
Look at the path it is trying to use to run nvcc. It looks like you've set your `CUDA_HOME`/`CUDA_PATH` variables wrongly as that's how PyTorch locates CUDA.
As this is in relation to your other issue please reply there rather than creating new issues. Closing this.
